##
POST localhost:8080/shorten
Content-Type: application/json

{
  "url": "https://docs.google.com/presentation/d/1H3m3ArVdAVuvKHO7jjq4ctCgVitzgpJ30k8sX4QtpOc/edit?slide=id.p#slide=id.p"
}

###
GET localhost:8080/stats/short.ly/1902956044
Content-Type: application/json

###
GET localhost:8080/short.ly/1902956044
Content-Type: application/json